- hosts: all
  become: true
  tasks:
   - name: first file
     stat:
       path: /file1/def
     register: first
   - name: second file
     stat:
       path: /file2/def2
     register: second
   - debug:
       msg: "File compare"


