- hosts: all
  become: true
  tasks:
   - name: Generate diff
     command: diff  /file1/def  /file2/def2
     register: diff_result
   - name: Show diff result
   - debug:
     msg: "{{diff_result.stdout}}"
     
   
