- hosts: all
  become: true
  tasks:
   - name: first file
     stat:
       path: /file1/def
     register: result
   - name: second file
     stat:
       path: /file2/def2
     register: result
   - debug:
       var: result
       msg: "{{result.stdout}}"


